name: Demo Deploy Theme
on:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: TryGhost/action-deploy-theme@v1.0.0
        with:
          api-url: ${{ secrets.DEMO_GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.DEMO_GHOST_ADMIN_API_KEY }}
